apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |-
    # Port to use for the default listener
    port 1883

    # Allow anonymous users to connect
    allow_anonymous true
